FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

# systémové závislosti
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    gcc \
    postgresql-client \
    netcat-traditional \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements-dev.txt /code/
RUN pip install --upgrade pip && \
    pip install -r requirements.txt && \
    pip install -r requirements-dev.txt

COPY . /code/

# Konvertovat konce řádků a nastavit oprávnění pro skripty
RUN apt-get update && apt-get install -y dos2unix && \
    dos2unix /code/entrypoint.sh /code/wait-for-fhir.sh && \
    chmod +x /code/entrypoint.sh /code/wait-for-fhir.sh && \
    apt-get remove -y dos2unix && apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8000
