# Generated by Django 4.2.26 on 2025-11-28 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("specialization", models.CharField(max_length=100)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "doctors",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("equipment_code", models.CharField(max_length=50, unique=True)),
                ("category", models.CharField(max_length=100)),
                ("purchase_date", models.DateField()),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "lifetime_hours",
                    models.IntegerField(help_text="Celková životnost v hodinách"),
                ),
                (
                    "used_hours",
                    models.IntegerField(default=0, help_text="Využité hodiny"),
                ),
                ("maintenance_date", models.DateField(blank=True, null=True)),
                ("is_operational", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "equipment",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hours_used", models.DecimalField(decimal_places=2, max_digits=5)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operating_rooms.equipment",
                    ),
                ),
            ],
            options={
                "db_table": "equipment_usage",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "ean_code",
                    models.CharField(
                        help_text="EAN-13 čárový kód", max_length=13, unique=True
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                (
                    "unit",
                    models.CharField(
                        help_text="Jednotka (ks, balení, atd.)", max_length=20
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_quantity", models.IntegerField(default=0)),
                ("minimum_stock", models.IntegerField(default=10)),
                ("is_disposable", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "materials",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity_used", models.IntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "scanned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Čas skenování EAN kódu"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operating_rooms.material",
                    ),
                ),
            ],
            options={
                "db_table": "material_usage",
            },
        ),
        migrations.CreateModel(
            name="OperatingRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("room_number", models.CharField(max_length=20, unique=True)),
                ("floor", models.IntegerField()),
                ("capacity", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "operating_rooms",
                "ordering": ["room_number"],
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("operation_type", models.CharField(max_length=200)),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Naplánováno"),
                            ("in_progress", "Probíhá"),
                            ("completed", "Dokončeno"),
                            ("cancelled", "Zrušeno"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_emergency", models.BooleanField(default=False)),
                (
                    "assisting_doctors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assisted_operations",
                        to="operating_rooms.doctor",
                    ),
                ),
                (
                    "operating_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="operating_rooms.operatingroom",
                    ),
                ),
            ],
            options={
                "db_table": "operations",
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_number", models.CharField(max_length=20, unique=True)),
                ("date_of_birth", models.DateField()),
                ("diagnosis", models.TextField()),
                ("medical_history", models.TextField(blank=True)),
            ],
            options={
                "db_table": "patients",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="PerioperativeProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("complications", models.TextField(blank=True)),
                ("procedure_notes", models.TextField()),
                ("anesthesia_type", models.CharField(max_length=100)),
                (
                    "total_staff_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_equipment_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_material_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "equipment_used",
                    models.ManyToManyField(
                        through="operating_rooms.EquipmentUsage",
                        to="operating_rooms.equipment",
                    ),
                ),
                (
                    "materials_used",
                    models.ManyToManyField(
                        through="operating_rooms.MaterialUsage",
                        to="operating_rooms.material",
                    ),
                ),
                (
                    "operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol",
                        to="operating_rooms.operation",
                    ),
                ),
            ],
            options={
                "db_table": "perioperative_protocols",
            },
        ),
        migrations.AddField(
            model_name="operation",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="operating_rooms.patient",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="primary_doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_operations",
                to="operating_rooms.doctor",
            ),
        ),
        migrations.AddField(
            model_name="materialusage",
            name="protocol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="operating_rooms.perioperativeprotocol",
            ),
        ),
        migrations.AddField(
            model_name="equipmentusage",
            name="protocol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="operating_rooms.perioperativeprotocol",
            ),
        ),
    ]
