# Generated by Django 4.2.26 on 2025-11-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operating_rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Název nástroje nebo materiálu", max_length=200
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Kategorie (např. Všeobecná Chirurgie, Ortopedie/Trauma)",
                        max_length=100,
                    ),
                ),
                (
                    "inventory_code",
                    models.CharField(
                        blank=True,
                        help_text="Fiktivní inventární kód",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "sterilization_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cena sterilizace v Kč na použití",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "udi_code",
                    models.CharField(
                        blank=True,
                        help_text="UDI DataMatrix kód (GS1 formát)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0, help_text="Aktuální množství na skladě"
                    ),
                ),
                (
                    "lifespan",
                    models.IntegerField(
                        blank=True, help_text="Životnost nástroje", null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("použití", "Použití"),
                            ("dní", "Dní"),
                            ("hodin", "Hodin"),
                        ],
                        default="použití",
                        help_text="Jednotka životnosti",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("good", "Dobrý stav"),
                            ("warning", "Varování"),
                            ("critical", "Kritický"),
                        ],
                        default="good",
                        help_text="Stav zásob",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Dodatečný popis"),
                ),
            ],
            options={
                "verbose_name": "Operační nástroj",
                "verbose_name_plural": "Operační nástroje",
                "db_table": "operation_tools",
                "ordering": ["category", "name"],
            },
        ),
    ]
