# Generated by Django 4.2.26 on 2025-11-29 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operating_rooms", "0002_operation_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="operating_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="operating_rooms.operatingroom",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="operation_type",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="operation",
            name="primary_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_operations",
                to="operating_rooms.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="scheduled_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="operation",
            name="scheduled_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
