# Generated by Django 4.2.26 on 2025-11-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operating_rooms", "0002_operationtool"),
        ("operating_rooms", "0003_alter_operation_operating_room_and_more"),
    ]

    operations = []
