# Generated by Django 4.2.26 on 2025-11-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operating_rooms", "0004_merge_20251129_1307"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="fhir_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="fhir_last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="fhir_resource_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="fhir_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="fhir_last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="fhir_resource_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="fhir_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="fhir_last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="fhir_resource_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operatingroom",
            name="fhir_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="operatingroom",
            name="fhir_last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operatingroom",
            name="fhir_resource_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operation",
            name="fhir_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="fhir_last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operation",
            name="fhir_resource_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="fhir_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="fhir_last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="fhir_resource_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
